2023-02-23 18:14:27 current train algo_env is PPOMicroRTSShare
2023-02-23 18:14:27 has no model data and starts a new train
2023-02-23 18:17:36 current train algo_env is PPOMicroRTSShare
2023-02-23 18:17:36 has no model data and starts a new train
2023-02-23 18:18:42 current train algo_env is PPOMicroRTSShare
2023-02-23 18:18:42 has no model data and starts a new train
2023-02-23 18:19:53 current train algo_env is PPOMicroRTSShare
2023-02-23 18:19:53 has no model data and starts a new train
2023-02-23 18:20:43 current train algo_env is PPOMicroRTSShare
2023-02-23 18:20:43 has no model data and starts a new train
2023-02-23 18:20:45 start trainer processid 41308 trainerid 0
2023-02-23 18:20:45 start sampler processid 47372 samplerid 0
2023-02-23 18:20:45 start sampler processid 47592 samplerid 1
2023-02-23 18:20:45 start checker processid 44784
2023-02-23 18:20:45 start run train_main_local main process id is 47776
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\train_main_local.py", line 201, in <module>\n    if utils.exit_run():\n', '  File "G:\\项目仓库\\drl\\libs\\utils.py", line 15, in exit_run\n    path = os.path.abspath(os.path.dirname(__file__) + \'/\' + \'../\')\n', 'KeyboardInterrupt\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\sampler.py", line 70, in process_function\n    exps_list = sample_agent.sample_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 313, in sample_env\n    unit_mask = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:49:59 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\checker.py", line 68, in process_function\n    infos = check_agent.check_env()\n', '  File "G:\\项目仓库\\drl\\algo_envs\\ppo_microrts_share.py", line 348, in check_env\n    unit_masks = np.array(self.env.vec_client.getUnitLocationMasks()).reshape(self.num_check_envs, -1)\n', 'jpype._core.JVMNotRunning: Java Virtual Machine is not running\n\n']
2023-02-23 19:50:00 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\train_main_local.py", line 231, in <module>\n    if exps_redis_cache.get_exps_length() >= args_dict[\'len_sample_queue\']:\n', '  File "G:\\项目仓库\\drl\\libs\\redis_cache.py", line 170, in get_exps_length\n    length = self.conn.llen(RedisCache.exps_name)\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\site-packages\\redis\\commands\\core.py", line 2586, in llen\n    return self.execute_command("LLEN", name)\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\site-packages\\redis\\client.py", line 1238, in execute_command\n    return conn.retry.call_with_retry(\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\site-packages\\redis\\retry.py", line 46, in call_with_retry\n    return do()\n', 'KeyboardInterrupt\n']
2023-02-23 19:50:02 Exception: ['Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\train_main_local.py", line 231, in <module>\n    if exps_redis_cache.get_exps_length() >= args_dict[\'len_sample_queue\']:\n', '  File "G:\\项目仓库\\drl\\libs\\redis_cache.py", line 170, in get_exps_length\n    length = self.conn.llen(RedisCache.exps_name)\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\site-packages\\redis\\commands\\core.py", line 2586, in llen\n    return self.execute_command("LLEN", name)\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\site-packages\\redis\\client.py", line 1235, in execute_command\n    conn = self.connection or pool.get_connection(command_name, **options)\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\site-packages\\redis\\connection.py", line 1377, in get_connection\n    self._checkpid()\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\site-packages\\redis\\connection.py", line 1363, in _checkpid\n    if self.pid != os.getpid():\n', 'KeyboardInterrupt\n']
2023-02-23 19:50:36 Exception: ['Traceback (most recent call last):\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\multiprocessing\\connection.py", line 312, in _recv_bytes\n    nread, err = ov.GetOverlappedResult(True)\n', 'BrokenPipeError: [WinError 109] 管道已结束。\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "G:\\项目仓库\\drl\\train_main_local\\train_main_local.py", line 238, in <module>\n    trainer_version = model_dict[0]\n', '  File "<string>", line 2, in __getitem__\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\multiprocessing\\managers.py", line 810, in _callmethod\n    kind, result = conn.recv()\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\multiprocessing\\connection.py", line 250, in recv\n    buf = self._recv_bytes()\n', '  File "C:\\Users\\wshil\\anaconda3\\envs\\drl\\lib\\multiprocessing\\connection.py", line 321, in _recv_bytes\n    raise EOFError\n', 'EOFError\n']
